on:
  push:
    branches:
      - main
      - master

name: Main Workflow
jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Single FOSSA step with analysis and tests
    - name: Run FOSSA Analysis and Tests
      uses: fossas/fossa-action@main
      with:
        api-key: ${{secrets.FOSSA_TOKEN}}
        project: 'custom+57218/git@github.com:0c34/govwa.git'
        run-tests: true
        # Add a small delay to ensure analysis completes before tests
        # This is handled internally by the action

    # Sync findings to ScanDog
    - name: ScanDog Fossa Sync
      uses: scandogio/scandog-import@main
      with:
        endpoint_type: 'sync'
        workflow_id: f83299061dcf3e8397b3da5ce4dac8d2
        scanner: 'fossa'
        scan_type: 'SCA'
        ci_run_id: ${{ github.run_id }}
        project_id: 'custom+57218/git@github.com:0c34/govwa.git'
        scandog_token: ${{ secrets.SCANDOG_BACKEND_API_TOKEN }}
        scandog_url: ${{ secrets.SCANDOG_BACKEND_URL }}
