on:
  push:
    branches:
      - main
      - master

name: Main Workflow
jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Install FOSSA CLI v3
    - name: Install FOSSA CLI v3
      run: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
        echo "$HOME/.fossa/bin" >> $GITHUB_PATH
    
    # Run FOSSA analysis
    - name: Run FOSSA Analysis
      run: |
        echo "Running FOSSA analysis for project: git+github.com/DevSecOpsOrg/govwa"
        fossa analyze --project git+github.com/DevSecOpsOrg/govwa
        echo "FOSSA analysis completed successfully"
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_TOKEN }}
    
    # Run FOSSA tests with detailed output
    - name: Run FOSSA Tests
      id: fossa-tests
      run: |
        echo "Running FOSSA tests for project: git+github.com/DevSecOpsOrg/govwa"
        if fossa test --project git+github.com/DevSecOpsOrg/govwa; then
          echo "FOSSA tests passed - no issues found"
          echo "fossa_status=success" >> $GITHUB_OUTPUT
        else
          echo "FOSSA tests completed with findings (this is expected for security scanning)"
          echo "fossa_status=findings" >> $GITHUB_OUTPUT
        fi
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_TOKEN }}
      continue-on-error: true
    
    # Display FOSSA test results
    - name: Display FOSSA Results
      run: |
        echo "FOSSA test status: ${{ steps.fossa-tests.outputs.fossa_status }}"
        if [ "${{ steps.fossa-tests.outputs.fossa_status }}" = "findings" ]; then
          echo "⚠️  FOSSA found compliance/security issues - check the logs above for details"
        else
          echo "✅ FOSSA tests passed - no issues found"
        fi
    
    # Sync findings to ScanDog
    - name: ScanDog Fossa Sync
      uses: scandogio/scandog-import@main
      with:
        endpoint_type: 'sync'
        workflow_id: f83299061dcf3e8397b3da5ce4dac8d2
        scanner: 'fossa'
        scan_type: 'SCA'
        ci_run_id: ${{ github.run_id }}
        project_id: 'git+github.com/DevSecOpsOrg/govwa'
        scandog_token: ${{ secrets.SCANDOG_BACKEND_API_TOKEN }}
        scandog_url: ${{ secrets.SCANDOG_BACKEND_URL }}
