on:
  push:
    branches:
      - main
      - master

name: Main Workflow
jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Install FOSSA CLI
    - name: Install FOSSA CLI
      run: |
        curl https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
        echo "$HOME/.fossa/bin" >> $GITHUB_PATH
    
    # Verify FOSSA CLI installation
    - name: Verify FOSSA CLI
      run: |
        fossa --version
    
    # Run FOSSA analysis
    - name: Run FOSSA Analysis
      run: |
        fossa analyze --project git+github.com/DevSecOpsOrg/govwa
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_TOKEN }}
    
    # Run FOSSA tests
    - name: Run FOSSA Tests
      run: |
        fossa test --project git+github.com/DevSecOpsOrg/govwa
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_TOKEN }}
    
    # Sync findings to ScanDog
    - name: ScanDog Fossa Sync
      uses: scandogio/scandog-import@main
      with:
        endpoint_type: 'sync'
        workflow_id: f83299061dcf3e8397b3da5ce4dac8d2
        scanner: 'fossa'
        scan_type: 'SCA'
        ci_run_id: ${{ github.run_id }}
        project_id: 'git+github.com/DevSecOpsOrg/govwa'
        scandog_token: ${{ secrets.SCANDOG_BACKEND_API_TOKEN }}
        scandog_url: ${{ secrets.SCANDOG_BACKEND_URL }}
