on:
  push:
    branches:
      - main
      - master

name: Main Workflow
jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Install FOSSA CLI v3 with better error handling
    - name: Install FOSSA CLI v3
      run: |
        set -e
        echo "Installing FOSSA CLI v3..."
        
        # Create local bin directory
        mkdir -p $HOME/.local/bin
        
        # Download and install FOSSA CLI v3
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
        
        # Add to PATH
        echo "$HOME/.fossa/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        echo "FOSSA CLI v3 installed successfully"
    
    # Verify installation
    - name: Verify FOSSA CLI Installation
      run: |
        fossa --version
        echo "FOSSA CLI is ready to use"
    
    # Run FOSSA analysis
    - name: Run FOSSA Analysis
      run: |
        echo "Running FOSSA analysis for project: git+github.com/DevSecOpsOrg/govwa"
        fossa analyze --project git+github.com/DevSecOpsOrg/govwa
        echo "FOSSA analysis completed successfully"
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_TOKEN }}
    
    # Run FOSSA tests
    - name: Run FOSSA Tests
      run: |
        echo "Running FOSSA tests for project: git+github.com/DevSecOpsOrg/govwa"
        fossa test --project git+github.com/DevSecOpsOrg/govwa
        echo "FOSSA tests completed successfully"
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_TOKEN }}
    
    # Sync findings to ScanDog
    - name: ScanDog Fossa Sync
      uses: scandogio/scandog-import@main
      with:
        endpoint_type: 'sync'
        workflow_id: f83299061dcf3e8397b3da5ce4dac8d2
        scanner: 'fossa'
        scan_type: 'SCA'
        ci_run_id: ${{ github.run_id }}
        project_id: 'git+github.com/DevSecOpsOrg/govwa'
        scandog_token: ${{ secrets.SCANDOG_BACKEND_API_TOKEN }}
        scandog_url: ${{ secrets.SCANDOG_BACKEND_URL }}
