# Scanners: opengrep
# Generated for github by ScanDog
name: sast Scanner Pipeline
on:
  push:
    branches:
      - master

jobs:
  scandog_opengrep_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Opengrep
        run: |
          apt-get update && apt-get install -y curl jq
          latest_version=$(curl --silent "https://api.github.com/repos/opengrep/opengrep/releases/latest" | jq -r .tag_name)
          curl -L -o opengrep "https://github.com/opengrep/opengrep/releases/download/${latest_version}/opengrep_manylinux_x86"
          chmod +x opengrep
          mv opengrep /usr/local/bin/opengrep
      - name: Run Opengrep
        run: opengrep scan --metrics on --config auto --json-output=opengrep.json .
      - name: Import results to ScanDog
        uses: scandogio/scandog-import@v1.0
        with:
          ci_run_id: ${{ github.run_id }}
          report_file: opengrep.json
          workflow_id: "2dc21a8397dea6d8f9779cb1307c6a61"
          scan_type: SAST
          scanner: opengrep
          backend_api_token: ${{ secrets.SCANDOG_BACKEND_API_TOKEN }}
          backend_url: ${{ secrets.SCANDOG_BACKEND_URL }}
