# Combined configuration from 2 templates
# Scanners: Gosec, grype
# Generated for GITHUB by ScanDog
name: Combined Security Scanner Pipeline
on:
  push:
    branches:
      - master

jobs:
# Jobs from template: Gosec
  scandog_gosec_scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt json -out gosec.json ./...'
      - name: Import results to ScanDog
        uses: scandogio/scandog-import@v1.0
        with:
          ci_run_id: ${{ github.run_id }}
          report_file: gosec.json
          workflow_id: "cf7208e81ee28fbf3d4a3fef7093da5a"
          scan_type: SAST
          scanner: Gosec
          backend_api_token: ${{ secrets.SCANDOG_BACKEND_API_TOKEN }}
          backend_url: ${{ secrets.SCANDOG_BACKEND_URL }}
# Jobs from template: grype
  scandog_grype_sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Grype
        uses: anchore/scan-action@v6
        with:
          path: .
          output-format: json
          output-file: grype-results.json
          fail-build: false
      - name: Import results to ScanDog
        uses: scandogio/scandog-import@v1.0
        with:
          ci_run_id: ${{ github.run_id }}
          report_file: grype-results.json
          workflow_id: "cf7208e81ee28fbf3d4a3fef7093da5a"
          scan_type: SCA
          scanner: grype
          backend_api_token: ${{ secrets.SCANDOG_BACKEND_API_TOKEN }}
          backend_url: ${{ secrets.SCANDOG_BACKEND_URL }}
